# Generated by Django 4.2.4 on 2023-12-21 14:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import meineimmobilien.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('commercial_lot', 'Gewerbegrundstück'), ('lot', 'Grundstück'), ('house', 'Haus'), ('hotel', 'Hotel'), ('pension', 'Pension'), ('apartment', 'Wohnung'), ('income_house', 'Zinshaus')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('image_main', models.ImageField(upload_to=meineimmobilien.models.project_directory_path_main_image)),
                ('image_main_thumbnail', models.ImageField(upload_to=meineimmobilien.models.project_directory_path_main_image)),
                ('expose_de', models.FileField(upload_to=meineimmobilien.models.project_directory_path_expose)),
                ('expose_en', models.FileField(upload_to=meineimmobilien.models.project_directory_path_expose)),
                ('expose_ru', models.FileField(upload_to=meineimmobilien.models.project_directory_path_expose)),
                ('title_de', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('description_de', ckeditor.fields.RichTextField()),
                ('description_en', ckeditor.fields.RichTextField()),
                ('description_ru', ckeditor.fields.RichTextField()),
                ('object_id', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition', models.CharField(blank=True, choices=[('very_good', 'Sehr gut'), ('good', 'Gut'), ('needs_renovation', 'Renovierungsbedürftig'), ('first_occupancy', 'Erstbezug')], default='very_good', max_length=100)),
                ('available_from_de', models.CharField(blank=True, default='', max_length=100)),
                ('available_from_en', models.CharField(blank=True, default='', max_length=100)),
                ('available_from_ru', models.CharField(blank=True, default='', max_length=100)),
                ('operating_costs_de', models.CharField(blank=True, default='', max_length=100)),
                ('operating_costs_en', models.CharField(blank=True, default='', max_length=100)),
                ('operating_costs_ru', models.CharField(blank=True, default='', max_length=100)),
                ('living_space', models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True)),
                ('has_basement', models.BooleanField(default=False)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('terraces', models.IntegerField(blank=True, null=True)),
                ('toilets', models.IntegerField(blank=True, null=True)),
                ('heating_type', models.CharField(blank=True, choices=[('oil', 'Öl'), ('gas', 'Gas'), ('district_heating', 'Fernwärme'), ('heat_pump', 'Wärmepumpe')], default='', max_length=50)),
                ('heating_system', models.CharField(blank=True, choices=[('underfloor_heating', 'Fußbodenheizung'), ('radiators', 'Heizkörper'), ('infrared', 'Infrarotheizung')], default='', max_length=50)),
                ('parking_type', models.CharField(blank=True, default='', max_length=100)),
                ('parking_anzahl', models.IntegerField(blank=True, null=True)),
                ('hwb_value', models.CharField(blank=True, default='', max_length=100)),
                ('hwb_class', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('umkreis', models.BooleanField(default=False)),
                ('meta_description_de', models.CharField(blank=True, default='', max_length=255)),
                ('meta_keywords_de', models.CharField(blank=True, default='', max_length=155)),
                ('meta_description_en', models.CharField(blank=True, default='', max_length=255)),
                ('meta_keywords_en', models.CharField(blank=True, default='', max_length=155)),
                ('meta_description_ru', models.CharField(blank=True, default='', max_length=255)),
                ('meta_keywords_ru', models.CharField(blank=True, default='', max_length=155)),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Imagethumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_thumbnail', models.ImageField(upload_to=meineimmobilien.models.project_directory_path_images)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meineimmobilien.project')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=meineimmobilien.models.project_directory_path_images)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meineimmobilien.project')),
            ],
        ),
        migrations.CreateModel(
            name='Dokumente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dokumente', models.FileField(upload_to=meineimmobilien.models.project_directory_path_dokumente)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meineimmobilien.project')),
            ],
        ),
    ]
