# Generated by Django 4.2.4 on 2024-01-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meineimmobilien', '0002_remove_project_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='parking_type',
        ),
        migrations.AddField(
            model_name='project',
            name='parking_einfahrt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='parking_garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='parking_liftgarage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='parking_nicht_bekannt',
            field=models.BooleanField(default=False),
        ),
    ]
