# Generated by Django 4.2.4 on 2024-01-09 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meineimmobilien', '0003_remove_project_parking_type_project_parking_einfahrt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagethumbnail',
            name='project',
        ),
        migrations.AddField(
            model_name='imagethumbnail',
            name='image',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='meineimmobilien.image'),
            preserve_default=False,
        ),
    ]
