# Generated by Django 4.2.4 on 2024-01-10 12:02

from django.db import migrations, models
import django.db.models.deletion
import meineimmobilien.models


class Migration(migrations.Migration):

    dependencies = [
        ('meineimmobilien', '0004_remove_imagethumbnail_project_imagethumbnail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumentethumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to=meineimmobilien.models.project_directory_path_dokumente)),
                ('dokumente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='meineimmobilien.dokumente')),
            ],
        ),
    ]
